apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-dashboard-backend-config
  namespace: gpu-dashboard
data:
  DATABASE_URL: "postgresql://<DB_USER>:<DB_PASSWORD>@<DB_HOST>:<DB_PORT>/<DB_NAME>"
  NAMESPACE: "gpu-dashboard"
  PROMETHEUS_ADDRESS: "<YOUR_PROMETHEUS_ADDRESS>"
  NODE_NAMES: "<YOUR_WORKER_NODE_NAMES>(comma-separated: e.g. k8s-worker-1,k8s-worker-2)"
  DATA_OBSERVER_URL: "<YOUR_DATAOBSERVER_SERVICE_URL>"
  CORS_ORIGINS: "<YOUR_FRONTEND_SERVICE_URL>"
  APP_PORT: "8000"
  SECRET_ALGORITHM: "HS256"
  LOG_LEVEL: "INFO"
  GPU_FETCH: "30"
  NFS_ADDRESS: "<YOUR_NFS_SERVER_IP>"
---
apiVersion: v1
kind: Secret
metadata:
  name: gpu-dashboard-backend-secret
  namespace: gpu-dashboard
type: Opaque
data:
  SECRET_KEY: <YOUR_BASE64_ENCODED_SECRET_KEY>